#!/usr/bin/perl
## adapted example code for IO::Uncompress::AnyUncompress which was written by Paul Marquess, pmqs at cpan.org
use strict ;
use warnings ;

use IO::Uncompress::AnyUncompress qw( anyuncompress $AnyUncompressError );

@ARGV = '-' unless @ARGV ;

foreach my $file (@ARGV) {

    anyuncompress $file       => '-',
               Transparent => 1,
               Strict      => 0,
         or die "Cannot uncompress '$file': $AnyUncompressError\n" ;

}
